# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/jysoft/python/cal/calculator.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_myCalculator(object):
    def setupUi(self, myCalculator):
        myCalculator.setObjectName("myCalculator")
        myCalculator.resize(311, 494)
        myCalculator.setStyleSheet("background-color: black")
        self.btn_7 = QtWidgets.QPushButton(myCalculator)
        self.btn_7.setGeometry(QtCore.QRect(20, 140, 61, 61))
        self.btn_7.setStyleSheet("background-color:rgb(25,25,25);\n"
"color: white;\n"
"border-radius: 8px;\n"
"font: 200 24pt \"Montserrat\";")
        self.btn_7.setObjectName("btn_7")
        self.btn_8 = QtWidgets.QPushButton(myCalculator)
        self.btn_8.setGeometry(QtCore.QRect(90, 140, 61, 61))
        self.btn_8.setStyleSheet("background-color:rgb(25,25,25);\n"
"color: white;\n"
"border-radius: 8px;\n"
"font: 200 24pt \"Montserrat\";")
        self.btn_8.setObjectName("btn_8")
        self.btn_9 = QtWidgets.QPushButton(myCalculator)
        self.btn_9.setGeometry(QtCore.QRect(160, 140, 61, 61))
        self.btn_9.setStyleSheet("background-color:rgb(25,25,25);\n"
"color: white;\n"
"border-radius: 8px;\n"
"font: 200 24pt \"Montserrat\";")
        self.btn_9.setObjectName("btn_9")
        self.btn_obelus = QtWidgets.QPushButton(myCalculator)
        self.btn_obelus.setGeometry(QtCore.QRect(230, 140, 61, 61))
        self.btn_obelus.setStyleSheet("background-color:rgb(25,25,25);\n"
"color: white;\n"
"border-radius: 8px;\n"
"font: 200 24pt \"Montserrat\";")
        self.btn_obelus.setObjectName("btn_obelus")
        self.btn_4 = QtWidgets.QPushButton(myCalculator)
        self.btn_4.setGeometry(QtCore.QRect(20, 210, 61, 61))
        self.btn_4.setStyleSheet("background-color:rgb(25,25,25);\n"
"color: white;\n"
"border-radius: 8px;\n"
"font: 200 24pt \"Montserrat\";")
        self.btn_4.setObjectName("btn_4")
        self.btn_times = QtWidgets.QPushButton(myCalculator)
        self.btn_times.setGeometry(QtCore.QRect(230, 210, 61, 61))
        self.btn_times.setStyleSheet("background-color:rgb(25,25,25);\n"
"color: white;\n"
"border-radius: 8px;\n"
"font: 200 24pt \"Montserrat\";")
        self.btn_times.setObjectName("btn_times")
        self.btn_5 = QtWidgets.QPushButton(myCalculator)
        self.btn_5.setGeometry(QtCore.QRect(90, 210, 61, 61))
        self.btn_5.setStyleSheet("background-color:rgb(25,25,25);\n"
"color: white;\n"
"border-radius: 8px;\n"
"font: 200 24pt \"Montserrat\";")
        self.btn_5.setObjectName("btn_5")
        self.btn_6 = QtWidgets.QPushButton(myCalculator)
        self.btn_6.setGeometry(QtCore.QRect(160, 210, 61, 61))
        self.btn_6.setStyleSheet("background-color:rgb(25,25,25);\n"
"color: white;\n"
"border-radius: 8px;\n"
"font: 200 24pt \"Montserrat\";")
        self.btn_6.setObjectName("btn_6")
        self.btn_3 = QtWidgets.QPushButton(myCalculator)
        self.btn_3.setGeometry(QtCore.QRect(160, 280, 61, 61))
        self.btn_3.setStyleSheet("background-color:rgb(25,25,25);\n"
"color: white;\n"
"border-radius: 8px;\n"
"font: 200 24pt \"Montserrat\";")
        self.btn_3.setObjectName("btn_3")
        self.btn_2 = QtWidgets.QPushButton(myCalculator)
        self.btn_2.setGeometry(QtCore.QRect(90, 280, 61, 61))
        self.btn_2.setStyleSheet("background-color:rgb(25,25,25);\n"
"color: white;\n"
"border-radius: 8px;\n"
"font: 200 24pt \"Montserrat\";")
        self.btn_2.setObjectName("btn_2")
        self.btn_minus = QtWidgets.QPushButton(myCalculator)
        self.btn_minus.setGeometry(QtCore.QRect(230, 280, 61, 61))
        self.btn_minus.setStyleSheet("background-color:rgb(25,25,25);\n"
"color: white;\n"
"border-radius: 8px;\n"
"font: 200 24pt \"Montserrat\";")
        self.btn_minus.setObjectName("btn_minus")
        self.btn_1 = QtWidgets.QPushButton(myCalculator)
        self.btn_1.setGeometry(QtCore.QRect(20, 280, 61, 61))
        self.btn_1.setStyleSheet("background-color:rgb(25,25,25);\n"
"color: white;\n"
"border-radius: 8px;\n"
"font: 200 24pt \"Montserrat\";")
        self.btn_1.setObjectName("btn_1")
        self.btn_0 = QtWidgets.QPushButton(myCalculator)
        self.btn_0.setGeometry(QtCore.QRect(20, 350, 61, 61))
        self.btn_0.setStyleSheet("background-color:rgb(25,25,25);\n"
"color: white;\n"
"border-radius: 8px;\n"
"font: 200 24pt \"Montserrat\";")
        self.btn_0.setObjectName("btn_0")
        self.btn_plus = QtWidgets.QPushButton(myCalculator)
        self.btn_plus.setGeometry(QtCore.QRect(160, 350, 61, 61))
        self.btn_plus.setStyleSheet("background-color:rgb(25,25,25);\n"
"color: white;\n"
"border-radius: 8px;\n"
"font: 200 24pt \"Montserrat\";")
        self.btn_plus.setObjectName("btn_plus")
        self.btn_point = QtWidgets.QPushButton(myCalculator)
        self.btn_point.setGeometry(QtCore.QRect(90, 350, 61, 61))
        self.btn_point.setStyleSheet("background-color:rgb(25,25,25);\n"
"color: white;\n"
"border-radius: 8px;\n"
"font: 200 24pt \"Montserrat\";")
        self.btn_point.setObjectName("btn_point")
        self.btn_equal = QtWidgets.QPushButton(myCalculator)
        self.btn_equal.setGeometry(QtCore.QRect(20, 420, 271, 61))
        self.btn_equal.setStyleSheet("background-color:rgb(25,25,25);\n"
"color: white;\n"
"border-radius: 8px;\n"
"font: 200 24pt \"Montserrat\";")
        self.btn_equal.setObjectName("btn_equal")
        self.display = QtWidgets.QTextBrowser(myCalculator)
        self.display.setGeometry(QtCore.QRect(20, 50, 271, 81))
        self.display.setStyleSheet("background-color:rgb(25,25,25);\n"
"color: white;\n"
"border-radius: 8px;\n"
"font: 87 24pt \"Montserrat\";\n"
"")
        self.display.setObjectName("display")
        self.btn_del = QtWidgets.QPushButton(myCalculator)
        self.btn_del.setGeometry(QtCore.QRect(230, 350, 61, 61))
        self.btn_del.setStyleSheet("background-color:rgb(25,25,25);\n"
"color: white;\n"
"border-radius: 8px;\n"
"font: 200 24pt \"Montserrat\";")
        self.btn_del.setObjectName("btn_del")
        self.display_result = QtWidgets.QTextEdit(myCalculator)
        self.display_result.setGeometry(QtCore.QRect(140, 10, 151, 31))
        self.display_result.setStyleSheet("background-color:rgb(25,25,25);\n"
"color: white;\n"
"border-radius: 8px;\n"
"font: 87 15pt \"Montserrat\";\n"
"\n"
"")
        self.display_result.setObjectName("display_result")

        self.retranslateUi(myCalculator)
        QtCore.QMetaObject.connectSlotsByName(myCalculator)

    def retranslateUi(self, myCalculator):
        _translate = QtCore.QCoreApplication.translate
        myCalculator.setWindowTitle(_translate("myCalculator", "myCalculator"))
        self.btn_7.setText(_translate("myCalculator", "7"))
        self.btn_8.setText(_translate("myCalculator", "8"))
        self.btn_9.setText(_translate("myCalculator", "9"))
        self.btn_obelus.setText(_translate("myCalculator", "÷"))
        self.btn_4.setText(_translate("myCalculator", "4"))
        self.btn_times.setText(_translate("myCalculator", "×"))
        self.btn_5.setText(_translate("myCalculator", "5"))
        self.btn_6.setText(_translate("myCalculator", "6"))
        self.btn_3.setText(_translate("myCalculator", "3"))
        self.btn_2.setText(_translate("myCalculator", "2"))
        self.btn_minus.setText(_translate("myCalculator", "-"))
        self.btn_1.setText(_translate("myCalculator", "1"))
        self.btn_0.setText(_translate("myCalculator", "0"))
        self.btn_plus.setText(_translate("myCalculator", "+"))
        self.btn_point.setText(_translate("myCalculator", "."))
        self.btn_equal.setText(_translate("myCalculator", "="))
        self.display.setHtml(_translate("myCalculator", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Montserrat\'; font-size:24pt; font-weight:80; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.btn_del.setText(_translate("myCalculator", "Del"))
